/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'xenxui' at '2016/10/13 上午 9:46' with Gradle 2.14
 *
 * @author xenxui, @date 2016/10/13 上午 9:46
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
